### ISSUE TITLE
I would like to volunteer!

### ISSUE THREAD

**Issue by notmorpheus** [sullivanmatt/bugalert#11]
Hello! I am a Security Engineer working with one of the famous Cloud Provider companies. I have about three years of experience in Networks Security and one year in blue team. Masters degree in Cybersec. In my recent experience, I've always found it difficult to effectively stay up to date with the latest vulnerabilities and POCs with Infosec twitter being the only place to get the information. I've tried various RSS feeds but they either break or we just don't know which feed to subscribe to. Therefore I am very interested in tackling this problem by being a part of this novel project. One of my latest projects for example with a terrible name https://github.com/notmorpheus/DDoS_Processor

**Comment by sullivanmatt** [comment]
Hey Ayan! Could you shoot me a message via one of the contact methods I have listed on Keybase with your email address? I'll get you onto the Slack. https://keybase.io/matthewsullivan

**Comment by sullivanmatt** [comment]
Closing for now having not gotten a response, but feel free to contact me if you want to help!
