### ISSUE TITLE
Maxim - I would like to volunteer!

### ISSUE THREAD

**Issue by maximbaele** [sullivanmatt/bugalert#12]
Hi, I read the blog post about this initiative and it really resonated with me. I would love to see how i can help out with this.

5+ years of security experience, mainly product security architecture and appsec management.
Volunteer in OWASP Belgium chapter and part of several security communities and knowledge sharing groups.

Linkedin: maximbaele

**Comment by sullivanmatt** [comment]
Hey Maxim! Could you shoot me a message via one of the contact methods I have listed on Keybase with your email address? I'll get you onto the Slack. https://keybase.io/matthewsullivan
