### ISSUE TITLE
Hi I would like to volunteer as well

### ISSUE THREAD

**Issue by brink668** [sullivanmatt/bugalert#13]
Hi, I read the blog post on reddit and have been thinking about the same issue for years, but your approach I think would be best.

I have been in the Cyber Security Space for over 10 years and already draft these types of notices both internally and to other colleagues including on various other platforms for security awareness. 

Linkedin: https://www.linkedin.com/in/richard-212135/
Personal Blog: https://www.richardwalz.com
Reddit: brink668

**Comment by sullivanmatt** [comment]
Hey Richard! Could you shoot me a message via one of the contact methods I have listed on Keybase with your email address? I'll get you onto the Slack. https://keybase.io/matthewsullivan

**Comment by mattlorimor** [comment]
Handled
