### ISSUE TITLE
Integrate with CISA alerts

### ISSUE THREAD

**Issue by mattcobb** [sullivanmatt/bugalert#14]
CISA has an alerting system:  https://www.cisa.gov/uscert/ncas/alerts. Those could be picked up and distributed here.

**Comment by sullivanmatt** [comment]
Thanks for opening an issue @mattcobb! I wanted to learn a bit more about this use-case. CISA _tends_ to be pretty slow to post notices. With the primary goal of this project being rapid notification, would the ability to source from CISA simply be to consolidate where people get alerts from? Or is there another benefit you were thinking of? I'd love to hear how this would be valuable in your processes.

Thanks!

**Comment by jakewarren** [comment]
I am not the OP but my vote would be to not include CISA alerts; CISA already has a couple of notification options available ([email](https://public.govdelivery.com/accounts/USDHSUSCERT/subscriber/new), [RSS](https://www.cisa.gov/uscert/ncas/alerts.xml)). And I agree that CISA tends to be slow to respond, the Log4J vulnerabilities being the most recent example. From my understanding the idea behind Bug Alert is to issue notices hours/days before orgs like CISA do. 

However updating existing notices from Bug Alert with a link to the CISA alerts (and other resources discovered afterwards) sounds like a great idea.
