### ISSUE TITLE
Volunteer if necessary

### ISSUE THREAD

**Issue by defau1t** [sullivanmatt/bugalert#15]
Two years in Cyber Sec, B.Sc in computer science. I'd be glad to volunteer to vet submissions.

Time zone, as I imagine that might be necessary for 24 hour coverage, is CST (GMT - 6) all year around.

**Comment by sullivanmatt** [comment]
Hey Robin! Could you shoot me a message via one of the contact methods I have listed on Keybase with your email address? I'll get you onto the Slack. https://keybase.io/matthewsullivan

**Comment by mattlorimor** [comment]
Handled
