### ISSUE TITLE
I would like to volunteer!

### ISSUE THREAD

**Issue by ethans** [sullivanmatt/bugalert#21]
Hi,
I've been in the cyber world for over 20 years, spending the past 16 in Check Point.
Currently I fill the position of R&D Security Leader, which basically means that I run the SDLC and I personally managed the effort surrounding the recent Log4j vulnerabilities.
I'd love to take an active part in this awesome project.
https://www.linkedin.com/in/ethans/
Ethan

**Comment by sullivanmatt** [comment]
Hi Ethan, I'm so glad you've reached out!

Could you shoot me a message via one of the contact methods I have listed on Keybase with your preferred email address? I'll get you onto the Slack. https://keybase.io/matthewsullivan

Thank you!

**Comment by sullivanmatt** [comment]
Actually, I'll just use the email address on your commits. Invite should be in your inbox!
