### ISSUE TITLE
I would like to volunteer!

### ISSUE THREAD

**Issue by colecornford** [sullivanmatt/bugalert#30]
Tell us about yourself. We want to ensure volunteers have relevant security expertise, so please include information and/or links related to your skillset or past projects.

Gday mate, Aussie AppSec professional. I run a consultancy down under and have 10 years of AppSec experience. I'm working on rewriting documentation for the OWASP CheatSheet and ZAP project, as well as performing source code reviews, DevSecOps reviews, and security education for Aussie developers.

Happy to help out, I think the AU timezone might be helpful to have someone available to review bugs in. :)

**Comment by sullivanmatt** [comment]
Gday!

Very happy to have you as a volunteer! And yes, we could definitely use some assistance with coverage in the Australian time zone 🙂

I have fired off a slack invite to the email address you have on your GitHub profile. Once you've joined up, we can get you put in all the right channels. See you there!
