### ISSUE TITLE
I would like to volunteer!

### ISSUE THREAD

**Issue by kaunix** [sullivanmatt/bugalert#34]
I'm a 20 year + sysadmin with an interest in IT security and analysis. my linkedin is www.linkedin.com/os2mac if you have any more questions please let me know.

**Comment by mattlorimor** [comment]
Broken LinkedIn link. Assuming this is the proper one: https://www.linkedin.com/in/os2mac/.

**Comment by kaunix** [comment]
Yeah sorry.

**Comment by kaunix** [comment]
is that a no?

**Comment by sullivanmatt** [comment]
Sorry @kaunix I've been really busy with work. It's a yes, I just need to get the time allocated to get you set up on everything. Stay tuned 👍

(Or @mattlorimor if you beat me to it...)

**Comment by kaunix** [comment]
oh. OK. I thought it was because I wasn't named Matt :)

**Comment by mattlorimor** [comment]
Added @kaunix to the org. I also invited you to the Slack workspace using the email listed in your github profile. If you are already there or use a different one, let me know, and I can add you to a couple private channels.

**Comment by kaunix** [comment]
Thanks Matt I’ll check in this evening. I’m out running errands atm.
