### ISSUE TITLE
No E-Mail

### ISSUE THREAD

**Issue by djalexz** [sullivanmatt/bugalert#35]
Hi, i don´t get an E-Mail.
The settings are corrrect.

![image](https://user-images.githubusercontent.com/11389551/151145665-aac8b958-ccbb-4415-a03e-7120edfcef37.png)

Thank you

**Comment by sullivanmatt** [comment]
Hi @djalexz,

Could you contact me with your registered email address using one of the contact methods on https://keybase.io/matthewsullivan ? I'll have a look. Thanks!

**Comment by sullivanmatt** [comment]
Thanks @djalexz, I got your message. I've identified the issue that caused this and I'll be working on getting a fix in place shortly.

**Comment by djalexz** [comment]
Thank you very much.

**Comment by n-pickering** [comment]
I seem to have the same or similar problem, I received the email for account verification from noreply@github.com
but not an alert email for https://bugalert.org/content/notices/2022-01-25-pkexec.html
Let me know if you need any more info from me.
And thanks for this nice project !

-- edit --
I got that SAP alert https://bugalert.org/content/notices/2022-02-08-sap.html so it seems to be resolved at least for me, this time..
Thanks again

**Comment by ethans** [comment]
@djalexz - did you get the email alert this morning about spring?

**Comment by n-pickering** [comment]
yes thanks
