### ISSUE TITLE
Link in pkexec email URL searches for title=log4j, no matches

### ISSUE THREAD

**Issue by jezzaaa** [sullivanmatt/bugalert#36]
Great service. Best of luck with it.

I just read the notice email for the pkexec bug. The link for "Discussion can be found on Github" links to
 https://github.com/sullivanmatt/bugalert/pulls?q=is%3Apr+in%3Atitle+log4j
which appears to be referencing log4j. The q= query string is "is:pr in:title log4j". The result is "no results matched your search." Perhaps the search term should be "is:pr in:title pkexec" for this bug?

**Comment by sullivanmatt** [comment]
Link hardcoded: https://github.com/BugAlertDotOrg/bugalert/blob/main/notice_communication/email_content.py#L614

Needs to be replaced with the {slug} variable during str format.

**Comment by Thelvaen** [comment]
Still the case with the Spring notice we just received.
Regards,

**Comment by sullivanmatt** [comment]
Resolved by https://github.com/BugAlertDotOrg/bugalert/pull/44
