### ISSUE TITLE
Volunteer

### ISSUE THREAD

**Issue by bboe** [sullivanmatt/bugalert#37]
Hi y'all,

I am interested in volunteering. I submitted an email with my credentials to Matt.

**Comment by mattlorimor-bnch** [comment]
This is a pretty old issue, @sullivanmatt. Did you handle this one, or was it missed?

**Comment by sullivanmatt** [comment]
Missed it, you mind handling @mattlorimor?

**Comment by mattlorimor** [comment]
Taking a second look at this, @sullivanmatt. I checked the Slack channel, and @bboe is already added to it (at least their email listed in the GitHub profile is). I'm closing this out.

Don't hesitate to re-open this or let me know if your access seems incorrect, @bboe.

**Comment by sullivanmatt** [comment]
With volunteers I also ensure we get them added to the volunteers group in github so they have merge rights.
