### ISSUE TITLE
Other donation channels?

### ISSUE THREAD

**Issue by malexmave** [sullivanmatt/bugalert#41]
Hi there. I really like BugAlert and would like to contribute some money (not a lot, so don't spend too much effort on this) to the operating costs. However, I live outside the US, so I don't have a Venmo account and would prefer not to open one just for this purpose. Is there any other way to send one-off donations? Something like PayPal, Stripe, GitHub sponsors, ...?

**Comment by sullivanmatt** [comment]
Hi @malexmave, I should probably take the time to get something like GitHub sponsors going. If PayPal works for you, I do have an account: sullivan.matt@gmail.com

Thanks!

**Comment by malexmave** [comment]
I sent you a small thank you via PayPal 😊.

**Comment by sullivanmatt** [comment]
I really appreciate that, thank you!

I'll leave this issue open as a reminder that we could add something like a PayPal donation button or the like.

**Comment by matthewsullivan-wf** [comment]
PayPal link added to https://bugalert.org/content/pages/financial-support.html

Thanks!

**Comment by sullivanmatt** [comment]
PayPal link added to https://bugalert.org/content/pages/financial-support.html

Thanks!
