### ISSUE TITLE
Broken link .html vs .md

### ISSUE THREAD

**Issue by tucuman** [sullivanmatt/bugalert#48]
https://github.com/BugAlertDotOrg/bugalert/blob/ae005765188b6a6a4391c75b567fab10cc2228f2/content/notices/2022-03-29-spring.md?plain=1#L14

**Comment by ethans** [comment]
Hi @tucuman ,
Thank you for your report.
Do you mean that the link in the email was to a .html but you actually reached a .md ?
Ethan

**Comment by tucuman** [comment]
Hi Ethan, thanks for responding. While browsing https://github.com/BugAlertDotOrg/bugalert/blob/main/content/notices/2022-03-29-spring.md I got a 404 hitting the link just there at line 14 - with no pelican processing at all. My bad I guess. 
Jan

**Comment by ethans** [comment]
Hi @tucuman ,
There was an issue for a short period of time yesterday. Sorry for the inconvenience.
Ethan
