### ISSUE TITLE
Document granular Atom feeds

### ISSUE THREAD

**Issue by ajh0912** [sullivanmatt/bugalert#5]
Interested to see if this project gets populated with accurate and quick information from community sources pre-CVE assignment, I far prefer a GitHub repo like this over services that keep private databases, although I'm curious to see how much the current setup could scale.

The Atom/RSS links go to `https://bugalert.org/feeds/all.atom.xml`

I can see in [pelicanconf.py](https://github.com/sullivanmatt/bugalert/blob/main/pelicanconf.py#L47-L49) that it allows using the category slug, meaning the link `https://bugalert.org/feeds/software-frameworks-libraries-and-components.atom.xml` works for querying just the 'Software Frameworks, Libraries, and Components' category.
It might be worth saying that somewhere?

Also could a slug feed be used for tags? For example `https://bugalert.org/feeds/critical-severity.atom.xml`, or if it's not possible to have tags and categories be searched at the same time: `https://bugalert.org/feeds/tag/critical-severity.atom.xml` and `https://bugalert.org/feeds/category/software-frameworks-libraries-and-components.atom.xml` or something similar.

**Comment by sullivanmatt** [comment]
> It might be worth saying that somewhere?

I agree!  Seems like perhaps the thing to do is make a page about the various Atom/RSS URLs and make the existing 'ATOM' link go there instead.  I will put it on the list, PRs welcome if you get the time before myself or @mattlorimor do though :)

> Also could a slug feed be used for tags? For example https://bugalert.org/feeds/critical-severity.atom.xml, or if it's not possible to have tags and categories be searched at the same time: https://bugalert.org/feeds/tag/critical-severity.atom.xml and https://bugalert.org/feeds/category/software-frameworks-libraries-and-components.atom.xml or something similar.

Yeah I like that, I'll have to check and see what Pelican is capable of. I'm betting it can.

**Comment by sullivanmatt** [comment]
Resolved in https://github.com/BugAlertDotOrg/bugalert/pull/22
