### ISSUE TITLE
I would like to volunteer!

### ISSUE THREAD

**Issue by amicone** [sullivanmatt/bugalert#50]
I have a decade as a security/privacy manager and now work at a FinTech company as a Security Operations Manager. Would be interested in adding my support and expertise to your project. In general, I can code and I have a small security engineering team and our company support pro-bono work by supplying paid hours.

**Comment by amicone** [comment]
Next steps?

**Comment by mattlorimor** [comment]
Sorry for the delay, @amicone. Is the email listed in your GitHub profile your preferred contact email to use to add you to things?

**Comment by amicone** [comment]
Nope, thanks for pointing that out, that was my last employment there. I have updated my public email address.

**Comment by mattlorimor** [comment]
Added @amicone to the Org.

I also invited your email listed on your GitHub profile to the Slack workspace. If that's not what I should have used and/or you are already in the Slack channel, let me know and I can get you added to a couple private channels.
