### ISSUE TITLE
Email with + don't work

### ISSUE THREAD

**Issue by ultramiker** [sullivanmatt/bugalert#7]
When you use the Gmail feature email.address+bugfix@gmail.com to create a unique email to ensure less spam/more security as all good IT professionals do. Bugfix will let you sign up but the magic link sent in email gets an error. 

Uh oh!
There is something wrong with your magic link (an error was returned from our API).

**Comment by sullivanmatt** [comment]
That's not intentional. Investigating...

**Comment by sullivanmatt** [comment]
@ultramiker all set, sorry about that!

**Comment by ultramiker** [comment]
Looks like I am in now thanks
