### ISSUE TITLE
Email Address Not Accepted

### ISSUE THREAD

**Issue by seoci** [sullivanmatt/bugalert#8]
Attempted to sign up and my email address was not accepted. It was bugalerts@mydomain.net (not the real domain, would prefer not to share it publicly). Error happened minutes before posting this in case that helps track it down on your end.

**Comment by seoci** [comment]
Just tried again and it worked this time. Please ignore.

**Comment by sullivanmatt** [comment]
This was a temporary issue related to fixing #7, the REST backend was down for just a couple of minutes due to a minor deploy hiccup. Sorry about that!
